spring.application.name=collabSphere-backend

server.port=8090

# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/collabsphere
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secretKey=Z2Q4V3ZpT2VqVnV2dDdkR1hZQmJxR0J5aHlPZkJ0dGxVcDg5V0VjY2xXQQ==

# Frontend URL
frontend.url=http://localhost:5173

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eryash790@gmail.com
spring.mail.password=wvksqptlqszpuspj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true